# ✅ core.Dockerfile — Warden, Portal, Vault, Moon (filtered installs)

# ─────────────────────────────────────────────
# 🌍 Base Builder for Node Services
# ─────────────────────────────────────────────
FROM node:23-slim AS noona-builder

WORKDIR /noona

# Create noona user
RUN groupadd -r noona && useradd -r -g noona -m -d /home/noona -s /bin/bash noona

# Install shared dev utils (used only in build context)
COPY utilities ./utilities

USER noona

# ─────────────────────────────────────────────
# 🛡 Noona-Warden
# ─────────────────────────────────────────────
FROM noona-builder AS noona-warden
USER root
WORKDIR /noona/services/warden

# Copy Warden logic
COPY services/warden ./

# Copy filtered package.json (generated by deploy.sh)
COPY services/warden/package.json ./package.json
RUN npm install

USER noona
CMD ["node", "initmain.mjs"]

# ─────────────────────────────────────────────
# 🎮 Noona-Portal
# ─────────────────────────────────────────────
FROM noona-builder AS noona-portal
USER root
WORKDIR /noona/services/portal

COPY services/portal ./
COPY services/portal/package.json ./package.json
RUN npm install

USER noona
CMD ["node", "initmain.mjs"]

# ─────────────────────────────────────────────
# 🧠 Noona-Vault
# ─────────────────────────────────────────────
FROM noona-builder AS noona-vault
USER root
WORKDIR /noona/services/vault

COPY services/vault ./
COPY services/vault/package.json ./package.json
RUN npm install

USER noona
CMD ["node", "initmain.mjs"]

# ─────────────────────────────────────────────
# 🌙 Noona-Moon (Combined frontend + backend)
# ─────────────────────────────────────────────
FROM noona-builder AS noona-moon

USER root
WORKDIR /noona/services/moon

# Copy full Moon service (backend + frontend)
COPY services/moon ./

# Validate frontend entrypoint
RUN test -f frontend/index.html || (echo "❌ Missing frontend/index.html" && exit 1)

# Frontend: build with filtered frontend deps
WORKDIR /noona/services/moon/frontend
COPY services/moon/frontend/package.json ./package.json
RUN npm install && npm run build

# Backend: install only backend deps
WORKDIR /noona/services/moon/backend
COPY services/moon/backend/package.json ./package.json
RUN npm install

USER noona
EXPOSE 3030
CMD ["node", "initmain.mjs"]
