import {
  mdiAlertOctagonOutline,
  mdiAlertOutline,
  mdiAt,
  mdiChartBoxOutline,
  mdiCheck,
  mdiCheckCircleOutline,
  mdiCircleOutline,
  mdiClockOutline,
  mdiCog,
  mdiCogPlay,
  mdiBird,
  mdiDownload,
  mdiInformationOutline,
  mdiCrystalBall,
  mdiHome,
  mdiMenu,
  mdiMoonWaningCrescent,
  mdiMagnify,
  mdiSafeSquare,
  mdiShieldCrown,
  mdiThemeLightDark,
  mdiTransitConnectionVariant,
  mdiWeatherSunny,
} from '@mdi/js';

const ICON_MAP = {
  'mdi-home': mdiHome,
  'mdi-cog-play': mdiCogPlay,
  'mdi-cog': mdiCog,
  'mdi-shield-crown': mdiShieldCrown,
  'mdi-safe-square': mdiSafeSquare,
  'mdi-transit-connection-variant': mdiTransitConnectionVariant,
  'mdi-chart-box-outline': mdiChartBoxOutline,
  'mdi-moon-waning-crescent': mdiMoonWaningCrescent,
  'mdi-weather-sunny': mdiWeatherSunny,
  'mdi-crow': mdiBird,
  'mdi-crystal-ball': mdiCrystalBall,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-check': mdiCheck,
  'mdi-theme-light-dark': mdiThemeLightDark,
  'mdi-menu': mdiMenu,
  'mdi-magnify': mdiMagnify,
  'mdi-clock-outline': mdiClockOutline,
  'mdi-alert-outline': mdiAlertOutline,
  'mdi-alert-octagon-outline': mdiAlertOctagonOutline,
  'mdi-download': mdiDownload,
  'mdi-at': mdiAt,
  'mdi-information-outline': mdiInformationOutline,
};

export function getIconPath(name) {
  return ICON_MAP[name] ?? mdiCircleOutline;
}
